using UnityEngine;

namespace Game.Map
{
    public class ObscuringItemFaderTrigger : MonoBehaviour
    {
        private void OnTriggerEnter2D(Collider2D collision)
        {
            ObscuringItemFader[] obscuringItemFader = collision.gameObject.GetComponentsInChildren<ObscuringItemFader>();

            if (obscuringItemFader.Length > 0)
            {
                for(int i=0; i<obscuringItemFader.Length; i++)
                {
                    obscuringItemFader[i].FadeOut();
                }
            }
        }

        private void OnTriggerExit2D(Collider2D collision)
        {
            ObscuringItemFader[] obscuringItemFader = collision.gameObject.GetComponentsInChildren<ObscuringItemFader>();

            if (obscuringItemFader.Length > 0)
            {
                for (int i = 0; i < obscuringItemFader.Length; i++)
                {
                    obscuringItemFader[i].FadeIn();
                }
            }

        }
    }
}
